//! TESTING-KEYS.md: a tickable line per key the window takes, generated
//! from `src/keys.rs` (the changeable ones, with their own keys on Windows
//! and Linux and on macOS) and the lists below (the fixed ones, and those
//! of the dialogs and boxes). Ticks survive.
//!
//! cargo run -p tsumugi --example make-keycheck            write it
//! cargo run -p tsumugi --example make-keycheck -- --check fail when out of date
//! cargo run -p tsumugi --example make-keycheck -- --stats how many are ticked

use std::collections::HashMap;
use std::path::Path;
use std::process::ExitCode;

#[allow(dead_code)]
#[path = "../src/keys.rs"]
mod keys;

const OUT: &str = "TESTING-KEYS.md";

const HEAD: &str = "# Key checklist

Generated by `cargo run -p tsumugi --example make-keycheck` from `crates/tsumugi/src/keys.rs` and the
example's own lists. Ticks are kept across regenerations; anything else here is overwritten. How many are
ticked is not written here (two pull requests ticking keys would collide): `-- --stats`.

A key is ticked when it did what the line says **and nothing else**: the shell did not also get it (no
stray character, no `^[` sequence), no other window opened, the pane with the keys is the same one.
Windows and Linux keys first; the macOS key is after `·`.
";

/// Fixed keys of the window, and the keys of its boxes: (section, key on
/// Windows and Linux, on macOS, what it does).
const FIXED: [(&str, &str, &str, &str); 32] = [
    ("The window, fixed", "Ctrl+Alt+1 … 9", "Cmd+1 … 9", "The Nth tab"),
    ("The window, fixed", "Alt+Left", "Cmd+Option+Left", "The keys to the pane on the left"),
    ("The window, fixed", "Alt+Right", "Cmd+Option+Right", "The keys to the pane on the right"),
    ("The window, fixed", "Alt+Up", "Cmd+Option+Up", "The keys to the pane above"),
    ("The window, fixed", "Alt+Down", "Cmd+Option+Down", "The keys to the pane below"),
    ("The window, fixed", "Alt+Shift+Left", "Cmd+Ctrl+Left", "Move the divider nearest the pane with the keys to the left"),
    ("The window, fixed", "Alt+Shift+Right", "Cmd+Ctrl+Right", "Move the divider nearest the pane with the keys to the right"),
    ("The window, fixed", "Alt+Shift+Up", "Cmd+Ctrl+Up", "Move the divider nearest the pane with the keys up"),
    ("The window, fixed", "Alt+Shift+Down", "Cmd+Ctrl+Down", "Move the divider nearest the pane with the keys down"),
    ("The new-session dialog", "Enter", "Enter", "Create in a new tab (on a button: press it)"),
    ("The new-session dialog", "Alt+Enter", "Option+Enter", "Create split to the right of the pane with the keys"),
    ("The new-session dialog", "Tab", "Tab", "In the folder: complete it from the list; complete, or elsewhere: the next field"),
    ("The new-session dialog", "Shift+Tab", "Shift+Tab", "The field before"),
    ("The new-session dialog", "Left / Right", "Left / Right", "On a way to start: the one beside it"),
    ("The new-session dialog", "Space", "Space", "Press the button that has the keys"),
    ("The new-session dialog", "Up / Down", "Up / Down", "Walk the folder list"),
    ("The new-session dialog", "Esc", "Esc", "Cancel"),
    ("The input box", "Ctrl+Enter", "Cmd+Enter", "Send the prompt"),
    ("The input box", "Ctrl+Shift+Enter", "Cmd+Shift+Enter", "Queue the prompt for when the session is done"),
    ("The input box", "Enter", "Enter", "A new line, not sent"),
    ("The input box", "Up / Down", "Up / Down", "The prompts sent before (in an empty box, or one showing a sent one)"),
    ("The input box", "Esc", "Esc", "Close the box, the keys back to the pane, the draft kept"),
    ("The search box", "Up / Down", "Up / Down", "Walk the entries"),
    ("The search box", "Enter", "Enter", "Do the entry picked"),
    ("The search box", "Esc", "Esc", "Close it"),
    ("The settings screen", "Esc", "Esc", "Leave the control that has the keys (a field as it was); with none, close the screen"),
    ("The settings screen", "Ctrl+Tab / Ctrl+PageDown", "Ctrl+Tab / Cmd+PageDown", "The next page"),
    ("The settings screen", "Ctrl+Shift+Tab / Ctrl+PageUp", "Ctrl+Shift+Tab / Cmd+PageUp", "The page before"),
    ("The settings screen", "Ctrl+F", "Cmd+F", "To the search"),
    ("The settings screen", "Tab / Shift+Tab", "Tab / Shift+Tab", "The search, the page's controls one by one, then Open settings.toml"),
    ("The settings screen", "Space / Enter", "Space / Enter", "Flip the switch or press the button that has the keys"),
    ("The settings screen", "Ctrl+,", "Cmd+,", "Open it (the changeable key above, while not moved)"),
];

fn lines() -> Vec<(String, String)> {
    let mut out = Vec::new();
    for (a, name, win, mac) in keys::NAMED {
        out.push(("The window, changeable (Settings → Keys, `[keys]`)".to_owned(), format!("`{win}` · `{mac}` — {} · `{name}`", keys::title(a))));
    }
    for (section, win, mac, what) in FIXED {
        out.push((section.to_owned(), format!("`{win}` · `{mac}` — {what}")));
    }
    out
}

fn marks(old: &str) -> HashMap<String, char> {
    old.lines()
        .filter_map(|l| {
            let rest = l.strip_prefix("- [")?;
            let mark = rest.chars().next()?;
            let body = rest.get(3..)?.trim_start();
            (mark == 'x' || mark == '~').then(|| (body.to_owned(), mark))
        })
        .collect()
}

fn write(lines: &[(String, String)], marks: &HashMap<String, char>) -> String {
    let mut out = String::from(HEAD);
    let mut section = "";
    for (s, l) in lines {
        if s != section {
            out.push_str(&format!("\n## {s}\n\n"));
            section = s;
        }
        out.push_str(&format!("- [{}] {l}\n", marks.get(l).copied().unwrap_or(' ')));
    }
    out
}

fn main() -> ExitCode {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let old = std::fs::read_to_string(root.join(OUT)).unwrap_or_default();
    let kept = marks(&old);
    let all = lines();
    let new = write(&all, &kept);
    match std::env::args().nth(1).as_deref() {
        Some("--check") => {
            if new == old {
                ExitCode::SUCCESS
            } else {
                eprintln!("{OUT} is out of date: cargo run -p tsumugi --example make-keycheck");
                ExitCode::FAILURE
            }
        }
        Some("--stats") => {
            let done = all.iter().filter(|(_, l)| kept.get(l) == Some(&'x')).count();
            println!("{done} / {} keys checked", all.len());
            ExitCode::SUCCESS
        }
        _ => match std::fs::write(root.join(OUT), new) {
            Ok(()) => ExitCode::SUCCESS,
            Err(e) => {
                eprintln!("{OUT}: {e}");
                ExitCode::FAILURE
            }
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_changeable_key_is_listed_and_ticks_kept() {
        let all = lines();
        assert_eq!(all.iter().filter(|(s, _)| s.starts_with("The window, changeable")).count(), keys::NAMED.len());
        let first = write(&all, &HashMap::new());
        let ticked = first.replacen("- [ ] `Ctrl+Shift+T`", "- [x] `Ctrl+Shift+T`", 1);
        assert_ne!(first, ticked);
        assert_eq!(write(&all, &marks(&ticked)), ticked);
    }
}
